name: Run Scripts
on:
  schedule:
    - cron: "0 14 * * 3" # Every Wednesday at 2PM UTC (10AM EST)
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      OL_ACCESS_KEY: ${{ secrets.OL_ACCESS_KEY }}
      OL_SECRET_KEY: ${{ secrets.OL_SECRET_KEY }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
    - run: python nyt_bestseller_collector.py
      env:
        NYT_API_KEY: ${{ secrets.NYT_API_KEY }}
    - run: python add_nyt_bestseller_tag.py --dry-run=False
    - run: python add_nyt_review_link.py --dry-run=False
